# Generated by Django 5.2 on 2025-05-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='Your_email',
            new_name='Emailngiz',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='Message',
            new_name='Habar',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='Your_name',
            new_name='Ismingiz',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='Phone',
            new_name='Nomer',
        ),
        migrations.AddField(
            model_name='booking',
            name='Odam',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
