# Generated by Django 5.2 on 2025-05-17 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_rename_your_email_booking_emailngiz_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='create_date',
        ),
    ]
