# Generated by Django 5.2 on 2025-04-28 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='description',
            new_name='dsc',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='title',
            new_name='full_name',
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(default=1, upload_to='service/'),
            preserve_default=False,
        ),
    ]
