# Generated by Django 5.1.7 on 2025-05-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_secbut'),
    ]

    operations = [
        migrations.AddField(
            model_name='secbut',
            name='icon_class',
            field=models.CharField(default='fa-utensils', max_length=50),
        ),
    ]
